model_id: "unsloth/Qwen2.5-VL-3B-Instruct"
lora_config:
  r: 16         
  lora_alpha: 32
  lora_dropout: 0
  bias: "none"
  loftq_config: None
  use_rslora: False
  target_modules: ["q_proj", "v_proj"]
  finetune_vision_layers: False
  finetune_language_layers: False,
  finetune_attention_modules: True, 
  finetune_mlp_modules: True
random_state: 01
tokenizer:
  add_special_tokens: true
prompts:
  vqg: "<img>{image}Hãy đặt 3 câu hỏi?"
  vqa: "<img>{image}{question}"
