# generation.yaml
# current: vlsp2023_train_data.json

# Required parameters
system_prompt: templates/generate_q/system_prompt.txt  # Path to system prompt file
user_prompt: templates/generate_q/user_prompt.txt  # Path to user prompt template file
image_folder: /mnt/VLAI_data/OpenViVQA/training-images/  # Path to folder containing images
input_json: data/extract_q/train_q_extracted.json  # Using your existing input path
output_json: data/generated/unsloth/generated_1q_train_7b.json  # Using your dedup_final_json

# Optional parameters
device: cuda  # Device to run inference on (cuda or cpu)
seed: 42  # Random seed for reproducibility
log_path: logs/generation_1q_train_unsloth.log  # Using your existing log_file
model_name: unsloth/Qwen2.5-VL-7B-Instruct
cache_dir: ../../weight/vlm/qwen2.5-vl-7b-instruct

# model_name = "/mnt/dataset1/pretrained_fm/unsloth_Qwen2.5-VL-7B-Instruct"
# cache_dir = None  # not needed when loading from a local dir 