# paraphrasing.yaml
# current: vlsp2023_train_data.json/ model_name: Qwen/Qwen2.5-VL-7B-Instruct

# Required parameters
system_prompt: templates/paraphase_q/system_prompt.txt
user_prompt: templates/paraphase_q/user_prompt.txt
input_json: /mnt/VLAI_data/OpenViVQA/vlsp2023_train_data.json
output_json: data/paraphrased/unsloth/paraphased_train_7b.json

# Optional parameters
device: cuda
seed: 42
log_path: logs/paraphrasing_train_unsloth.log
model_name: unsloth/Qwen2.5-VL-7B-Instruct
cache_dir: ../../weight/vlm/qwen2.5-vl-7b-instruct